import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

localStorage.setItem('auth_token', "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImFmYjhlZDhiYjc2ODAxZDkxZGM1NGQ0YzVjYmUzZDlhNjljMTllZDI0MzBlYjllYTcxOTFkYzZkMTAxOTczMzBiOTM2YzkzZmJhZTY5NjZkIn0.eyJhdWQiOiIyMSIsImp0aSI6ImFmYjhlZDhiYjc2ODAxZDkxZGM1NGQ0YzVjYmUzZDlhNjljMTllZDI0MzBlYjllYTcxOTFkYzZkMTAxOTczMzBiOTM2YzkzZmJhZTY5NjZkIiwiaWF0IjoxNTY4NTgzMDY3LCJuYmYiOjE1Njg1ODMwNjcsImV4cCI6MTYwMDIwNTQ2Nywic3ViIjoiNCIsInNjb3BlcyI6WyJlbXBsb3llZSJdfQ.iL0Frz0tqDNIskaIreMHI9yjmG8IVZOrCRqKgFXPeJ6EF3D4ZAQc2GtI_pXLZ12R7GB3nMIhci-n2QGNS5eSdJhzjy5hVavmgKKK3QBUwyK9re4EJ_T8aHsHlCVMHByOlswmzSg3diBtesQZXthc3PltsPfQLZ8x71o7zasOaXsvJ5Z2eUrKPRTH2W3YyDHwfZsr1smkA-cqv2xMsTIL01Me0j_YCOCYzN4zyn3hI8nD70ZRbNLqp68vutOxHsw7eYJ94m8SOKsy2JRrIhmcmNZy4hOLMQQZO0Ne39fSMRysCAqRdTSyMbN7ZIWkgssszFYnCaZvQbu6poo8JbR1C5h2T7v76n3PRLQVw0hfzUYU8f0Tq6zOZsPBQc5dq-tTDc7BIM22_r3akYQv3PZWdb9Yr1wl5OfrVmlXF8h91UlbSDfv7v3NDMUF2p09_h5VHKdLk6sKYnVLVVg2Ogf8mOEJh4kEzej336qb_mPaQzuBGqQuam2DfYD1naKwzxQq9bxIsmhe_Ae-62lWf7sUnF3FNYOM-22AfzFd5S2huy6bU1w53sR2wUS1c-afSc7S7xKEsbGTtWANlNtj3LoRg9IASixF6-mPAMOgZ80J8PEnhowaWFm31yVscXlHH2mR_CUUf5DzOzp41f0syZalFFDVJyDCfSjVPpvRrAiK7NM")

ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
